apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stable-diff-new-pv
  namespace: stable-diff-new
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 75Gi
  storageClassName: nfs-diff-webui # See kubectl get storageClass

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: stable-diff-new-pv
  namespace: stable-diff-new
spec:
  capacity:
    storage: 75Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany # ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-diff-webui
  nfs:
    path: /kubexports/nfs-diff-webui
    server: 10.90.1.1
